export const PERMISSIONS = {
  USERS_MANAGE: "users.manage",
  ROLES_MANAGE: "roles.manage",
  SCOPE_MANAGE: "scope.manage",
  CUSTOMERS_CREATE: "customers.create",
  CUSTOMERS_UPDATE: "customers.update",
  CUSTOMERS_DELETE: "customers.delete",
  PROSPECTS_CREATE: "prospects.create",
  PROSPECTS_UPDATE: "prospects.update",
  PROSPECTS_DELETE: "prospects.delete",
  PROSPECTS_CONVERT: "prospects.convert",
  ACTIVITIES_CREATE: "activities.create",
  ACTIVITIES_UPDATE: "activities.update",
  ACTIVITIES_COMPLETE: "activities.complete",
  ACTIVITIES_ASSIGN: "activities.assign",
  PRODUCTS_CREATE: "products.create",
  PRODUCTS_UPDATE: "products.update",
  PRODUCTS_DELETE: "products.delete",
  PRODUCTS_PRICE_EDIT: "products.price.edit",
  OPPORTUNITIES_CREATE: "opportunities.create",
  OPPORTUNITIES_UPDATE: "opportunities.update",
  OPPORTUNITIES_DELETE: "opportunities.delete",
  OPPORTUNITIES_PRICE_EDIT: "opportunities.price.edit",
  OPPORTUNITIES_ITEMS_CREATE: "opportunities.items.create",
  OPPORTUNITIES_ITEMS_UPDATE: "opportunities.items.update",
  OPPORTUNITIES_ITEMS_DELETE: "opportunities.items.delete",
};